---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/init

inputs:
- name: config-server
- name: version-semver

outputs:
- name: compiled-linux

params:
  GOOS: linux
  GOARCH: amd64

run:
  path: config-server/ci/tasks/build.sh
